language: python
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"

install:
  - pip install pip -U
  - pip install -e .
  - pip install pycodestyle
  - pip install coveralls

before_script:
  - "bash format.sh"

script: coverage run --source=slugify test.py

after_success: coveralls
