name: (CI)

on:
  push:
    branches:
      - ci

jobs:
  build:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: [3.6, 3.7, 3.8, 3.9, "3.10", pypy3]
    steps:
      - name: setup-python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install coveralls --upgrade
      - name: Run flake8
        run: |
          pip install flake8 --upgrade
          flake8 --exclude=migrations,tests --ignore=E501,E241,E225,E128 .
      - name: Run pycodestyle
        run: |
          pip install pycodestyle --upgrade
          pycodestyle --exclude=migrations,tests --ignore=E501,E241,E225,E128 .
      - name: Run test
        run: |
          coverage run --source=python test.py
      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
